# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dalvarez/Documents/repos/ratty

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dalvarez/Documents/repos/ratty

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dalvarez/Documents/repos/ratty/CMakeFiles /Users/dalvarez/Documents/repos/ratty//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dalvarez/Documents/repos/ratty/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ratty

# Build rule for target.
ratty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty
.PHONY : ratty

# fast build rule for target.
ratty/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/build
.PHONY : ratty/fast

#=============================================================================
# Target rules for targets named ratty_autogen_timestamp_deps

# Build rule for target.
ratty_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty_autogen_timestamp_deps
.PHONY : ratty_autogen_timestamp_deps

# fast build rule for target.
ratty_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty_autogen_timestamp_deps.dir/build.make CMakeFiles/ratty_autogen_timestamp_deps.dir/build
.PHONY : ratty_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ratty_autogen

# Build rule for target.
ratty_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty_autogen
.PHONY : ratty_autogen

# fast build rule for target.
ratty_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty_autogen.dir/build.make CMakeFiles/ratty_autogen.dir/build
.PHONY : ratty_autogen/fast

ratty_autogen/3YJK5W5UP7/qrc_shaders.o: ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.o

# target to build an object file
ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o

ratty_autogen/3YJK5W5UP7/qrc_shaders.i: ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.i

# target to preprocess a source file
ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i

ratty_autogen/3YJK5W5UP7/qrc_shaders.s: ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.s

# target to generate assembly for a file
ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s

ratty_autogen/mocs_compilation.o: ratty_autogen/mocs_compilation.cpp.o
.PHONY : ratty_autogen/mocs_compilation.o

# target to build an object file
ratty_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/mocs_compilation.cpp.o
.PHONY : ratty_autogen/mocs_compilation.cpp.o

ratty_autogen/mocs_compilation.i: ratty_autogen/mocs_compilation.cpp.i
.PHONY : ratty_autogen/mocs_compilation.i

# target to preprocess a source file
ratty_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/mocs_compilation.cpp.i
.PHONY : ratty_autogen/mocs_compilation.cpp.i

ratty_autogen/mocs_compilation.s: ratty_autogen/mocs_compilation.cpp.s
.PHONY : ratty_autogen/mocs_compilation.s

# target to generate assembly for a file
ratty_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/mocs_compilation.cpp.s
.PHONY : ratty_autogen/mocs_compilation.cpp.s

src/config/config.o: src/config/config.cpp.o
.PHONY : src/config/config.o

# target to build an object file
src/config/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/config.cpp.o
.PHONY : src/config/config.cpp.o

src/config/config.i: src/config/config.cpp.i
.PHONY : src/config/config.i

# target to preprocess a source file
src/config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/config.cpp.i
.PHONY : src/config/config.cpp.i

src/config/config.s: src/config/config.cpp.s
.PHONY : src/config/config.s

# target to generate assembly for a file
src/config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/config.cpp.s
.PHONY : src/config/config.cpp.s

src/core/pty.o: src/core/pty.cpp.o
.PHONY : src/core/pty.o

# target to build an object file
src/core/pty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/pty.cpp.o
.PHONY : src/core/pty.cpp.o

src/core/pty.i: src/core/pty.cpp.i
.PHONY : src/core/pty.i

# target to preprocess a source file
src/core/pty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/pty.cpp.i
.PHONY : src/core/pty.cpp.i

src/core/pty.s: src/core/pty.cpp.s
.PHONY : src/core/pty.s

# target to generate assembly for a file
src/core/pty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/pty.cpp.s
.PHONY : src/core/pty.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render/font_manager.o: src/render/font_manager.cpp.o
.PHONY : src/render/font_manager.o

# target to build an object file
src/render/font_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/font_manager.cpp.o
.PHONY : src/render/font_manager.cpp.o

src/render/font_manager.i: src/render/font_manager.cpp.i
.PHONY : src/render/font_manager.i

# target to preprocess a source file
src/render/font_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/font_manager.cpp.i
.PHONY : src/render/font_manager.cpp.i

src/render/font_manager.s: src/render/font_manager.cpp.s
.PHONY : src/render/font_manager.s

# target to generate assembly for a file
src/render/font_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/font_manager.cpp.s
.PHONY : src/render/font_manager.cpp.s

src/render/gl_renderer.o: src/render/gl_renderer.cpp.o
.PHONY : src/render/gl_renderer.o

# target to build an object file
src/render/gl_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/gl_renderer.cpp.o
.PHONY : src/render/gl_renderer.cpp.o

src/render/gl_renderer.i: src/render/gl_renderer.cpp.i
.PHONY : src/render/gl_renderer.i

# target to preprocess a source file
src/render/gl_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/gl_renderer.cpp.i
.PHONY : src/render/gl_renderer.cpp.i

src/render/gl_renderer.s: src/render/gl_renderer.cpp.s
.PHONY : src/render/gl_renderer.s

# target to generate assembly for a file
src/render/gl_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/gl_renderer.cpp.s
.PHONY : src/render/gl_renderer.cpp.s

src/render/glyph_atlas.o: src/render/glyph_atlas.cpp.o
.PHONY : src/render/glyph_atlas.o

# target to build an object file
src/render/glyph_atlas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/glyph_atlas.cpp.o
.PHONY : src/render/glyph_atlas.cpp.o

src/render/glyph_atlas.i: src/render/glyph_atlas.cpp.i
.PHONY : src/render/glyph_atlas.i

# target to preprocess a source file
src/render/glyph_atlas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/glyph_atlas.cpp.i
.PHONY : src/render/glyph_atlas.cpp.i

src/render/glyph_atlas.s: src/render/glyph_atlas.cpp.s
.PHONY : src/render/glyph_atlas.s

# target to generate assembly for a file
src/render/glyph_atlas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/glyph_atlas.cpp.s
.PHONY : src/render/glyph_atlas.cpp.s

src/ui/input_handler.o: src/ui/input_handler.cpp.o
.PHONY : src/ui/input_handler.o

# target to build an object file
src/ui/input_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/input_handler.cpp.o
.PHONY : src/ui/input_handler.cpp.o

src/ui/input_handler.i: src/ui/input_handler.cpp.i
.PHONY : src/ui/input_handler.i

# target to preprocess a source file
src/ui/input_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/input_handler.cpp.i
.PHONY : src/ui/input_handler.cpp.i

src/ui/input_handler.s: src/ui/input_handler.cpp.s
.PHONY : src/ui/input_handler.s

# target to generate assembly for a file
src/ui/input_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/input_handler.cpp.s
.PHONY : src/ui/input_handler.cpp.s

src/ui/main_window.o: src/ui/main_window.cpp.o
.PHONY : src/ui/main_window.o

# target to build an object file
src/ui/main_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/main_window.cpp.o
.PHONY : src/ui/main_window.cpp.o

src/ui/main_window.i: src/ui/main_window.cpp.i
.PHONY : src/ui/main_window.i

# target to preprocess a source file
src/ui/main_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/main_window.cpp.i
.PHONY : src/ui/main_window.cpp.i

src/ui/main_window.s: src/ui/main_window.cpp.s
.PHONY : src/ui/main_window.s

# target to generate assembly for a file
src/ui/main_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/main_window.cpp.s
.PHONY : src/ui/main_window.cpp.s

src/ui/split_container.o: src/ui/split_container.cpp.o
.PHONY : src/ui/split_container.o

# target to build an object file
src/ui/split_container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/split_container.cpp.o
.PHONY : src/ui/split_container.cpp.o

src/ui/split_container.i: src/ui/split_container.cpp.i
.PHONY : src/ui/split_container.i

# target to preprocess a source file
src/ui/split_container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/split_container.cpp.i
.PHONY : src/ui/split_container.cpp.i

src/ui/split_container.s: src/ui/split_container.cpp.s
.PHONY : src/ui/split_container.s

# target to generate assembly for a file
src/ui/split_container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/split_container.cpp.s
.PHONY : src/ui/split_container.cpp.s

src/ui/terminal_tab.o: src/ui/terminal_tab.cpp.o
.PHONY : src/ui/terminal_tab.o

# target to build an object file
src/ui/terminal_tab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_tab.cpp.o
.PHONY : src/ui/terminal_tab.cpp.o

src/ui/terminal_tab.i: src/ui/terminal_tab.cpp.i
.PHONY : src/ui/terminal_tab.i

# target to preprocess a source file
src/ui/terminal_tab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_tab.cpp.i
.PHONY : src/ui/terminal_tab.cpp.i

src/ui/terminal_tab.s: src/ui/terminal_tab.cpp.s
.PHONY : src/ui/terminal_tab.s

# target to generate assembly for a file
src/ui/terminal_tab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_tab.cpp.s
.PHONY : src/ui/terminal_tab.cpp.s

src/ui/terminal_widget.o: src/ui/terminal_widget.cpp.o
.PHONY : src/ui/terminal_widget.o

# target to build an object file
src/ui/terminal_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_widget.cpp.o
.PHONY : src/ui/terminal_widget.cpp.o

src/ui/terminal_widget.i: src/ui/terminal_widget.cpp.i
.PHONY : src/ui/terminal_widget.i

# target to preprocess a source file
src/ui/terminal_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_widget.cpp.i
.PHONY : src/ui/terminal_widget.cpp.i

src/ui/terminal_widget.s: src/ui/terminal_widget.cpp.s
.PHONY : src/ui/terminal_widget.s

# target to generate assembly for a file
src/ui/terminal_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_widget.cpp.s
.PHONY : src/ui/terminal_widget.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ratty_autogen"
	@echo "... ratty_autogen_timestamp_deps"
	@echo "... ratty"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_shaders.o"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_shaders.i"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_shaders.s"
	@echo "... ratty_autogen/mocs_compilation.o"
	@echo "... ratty_autogen/mocs_compilation.i"
	@echo "... ratty_autogen/mocs_compilation.s"
	@echo "... src/config/config.o"
	@echo "... src/config/config.i"
	@echo "... src/config/config.s"
	@echo "... src/core/pty.o"
	@echo "... src/core/pty.i"
	@echo "... src/core/pty.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render/font_manager.o"
	@echo "... src/render/font_manager.i"
	@echo "... src/render/font_manager.s"
	@echo "... src/render/gl_renderer.o"
	@echo "... src/render/gl_renderer.i"
	@echo "... src/render/gl_renderer.s"
	@echo "... src/render/glyph_atlas.o"
	@echo "... src/render/glyph_atlas.i"
	@echo "... src/render/glyph_atlas.s"
	@echo "... src/ui/input_handler.o"
	@echo "... src/ui/input_handler.i"
	@echo "... src/ui/input_handler.s"
	@echo "... src/ui/main_window.o"
	@echo "... src/ui/main_window.i"
	@echo "... src/ui/main_window.s"
	@echo "... src/ui/split_container.o"
	@echo "... src/ui/split_container.i"
	@echo "... src/ui/split_container.s"
	@echo "... src/ui/terminal_tab.o"
	@echo "... src/ui/terminal_tab.i"
	@echo "... src/ui/terminal_tab.s"
	@echo "... src/ui/terminal_widget.o"
	@echo "... src/ui/terminal_widget.i"
	@echo "... src/ui/terminal_widget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

