# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dalvarez/Documents/repos/ratty

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dalvarez/Documents/repos/ratty

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dalvarez/Documents/repos/ratty/CMakeFiles /Users/dalvarez/Documents/repos/ratty//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dalvarez/Documents/repos/ratty/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ratty

# Build rule for target.
ratty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty
.PHONY : ratty

# fast build rule for target.
ratty/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/build
.PHONY : ratty/fast

#=============================================================================
# Target rules for targets named ratty_autogen_timestamp_deps

# Build rule for target.
ratty_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty_autogen_timestamp_deps
.PHONY : ratty_autogen_timestamp_deps

# fast build rule for target.
ratty_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty_autogen_timestamp_deps.dir/build.make CMakeFiles/ratty_autogen_timestamp_deps.dir/build
.PHONY : ratty_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ratty_autogen

# Build rule for target.
ratty_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty_autogen
.PHONY : ratty_autogen

# fast build rule for target.
ratty_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty_autogen.dir/build.make CMakeFiles/ratty_autogen.dir/build
.PHONY : ratty_autogen/fast

#=============================================================================
# Target rules for targets named ratty_lib

# Build rule for target.
ratty_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty_lib
.PHONY : ratty_lib

# fast build rule for target.
ratty_lib/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ratty_lib.dir/build.make tests/CMakeFiles/ratty_lib.dir/build
.PHONY : ratty_lib/fast

#=============================================================================
# Target rules for targets named test_terminal

# Build rule for target.
test_terminal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_terminal
.PHONY : test_terminal

# fast build rule for target.
test_terminal/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_terminal.dir/build.make tests/CMakeFiles/test_terminal.dir/build
.PHONY : test_terminal/fast

#=============================================================================
# Target rules for targets named test_mouse

# Build rule for target.
test_mouse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mouse
.PHONY : test_mouse

# fast build rule for target.
test_mouse/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mouse.dir/build.make tests/CMakeFiles/test_mouse.dir/build
.PHONY : test_mouse/fast

#=============================================================================
# Target rules for targets named test_input

# Build rule for target.
test_input: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_input
.PHONY : test_input

# fast build rule for target.
test_input/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_input.dir/build.make tests/CMakeFiles/test_input.dir/build
.PHONY : test_input/fast

#=============================================================================
# Target rules for targets named test_splits

# Build rule for target.
test_splits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_splits
.PHONY : test_splits

# fast build rule for target.
test_splits/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_splits.dir/build.make tests/CMakeFiles/test_splits.dir/build
.PHONY : test_splits/fast

#=============================================================================
# Target rules for targets named test_splits_gl

# Build rule for target.
test_splits_gl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_splits_gl
.PHONY : test_splits_gl

# fast build rule for target.
test_splits_gl/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_splits_gl.dir/build.make tests/CMakeFiles/test_splits_gl.dir/build
.PHONY : test_splits_gl/fast

#=============================================================================
# Target rules for targets named test_scroll_gl

# Build rule for target.
test_scroll_gl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scroll_gl
.PHONY : test_scroll_gl

# fast build rule for target.
test_scroll_gl/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_scroll_gl.dir/build.make tests/CMakeFiles/test_scroll_gl.dir/build
.PHONY : test_scroll_gl/fast

#=============================================================================
# Target rules for targets named test_render

# Build rule for target.
test_render: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_render
.PHONY : test_render

# fast build rule for target.
test_render/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_render.dir/build.make tests/CMakeFiles/test_render.dir/build
.PHONY : test_render/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_config.dir/build.make tests/CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_tabbar

# Build rule for target.
test_tabbar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tabbar
.PHONY : test_tabbar

# fast build rule for target.
test_tabbar/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_tabbar.dir/build.make tests/CMakeFiles/test_tabbar.dir/build
.PHONY : test_tabbar/fast

#=============================================================================
# Target rules for targets named ratty_lib_autogen_timestamp_deps

# Build rule for target.
ratty_lib_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty_lib_autogen_timestamp_deps
.PHONY : ratty_lib_autogen_timestamp_deps

# fast build rule for target.
ratty_lib_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ratty_lib_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/ratty_lib_autogen_timestamp_deps.dir/build
.PHONY : ratty_lib_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ratty_lib_autogen

# Build rule for target.
ratty_lib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ratty_lib_autogen
.PHONY : ratty_lib_autogen

# fast build rule for target.
ratty_lib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/ratty_lib_autogen.dir/build.make tests/CMakeFiles/ratty_lib_autogen.dir/build
.PHONY : ratty_lib_autogen/fast

#=============================================================================
# Target rules for targets named test_terminal_autogen_timestamp_deps

# Build rule for target.
test_terminal_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_terminal_autogen_timestamp_deps
.PHONY : test_terminal_autogen_timestamp_deps

# fast build rule for target.
test_terminal_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_terminal_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_terminal_autogen_timestamp_deps.dir/build
.PHONY : test_terminal_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_terminal_autogen

# Build rule for target.
test_terminal_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_terminal_autogen
.PHONY : test_terminal_autogen

# fast build rule for target.
test_terminal_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_terminal_autogen.dir/build.make tests/CMakeFiles/test_terminal_autogen.dir/build
.PHONY : test_terminal_autogen/fast

#=============================================================================
# Target rules for targets named test_mouse_autogen_timestamp_deps

# Build rule for target.
test_mouse_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mouse_autogen_timestamp_deps
.PHONY : test_mouse_autogen_timestamp_deps

# fast build rule for target.
test_mouse_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mouse_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_mouse_autogen_timestamp_deps.dir/build
.PHONY : test_mouse_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_mouse_autogen

# Build rule for target.
test_mouse_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mouse_autogen
.PHONY : test_mouse_autogen

# fast build rule for target.
test_mouse_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mouse_autogen.dir/build.make tests/CMakeFiles/test_mouse_autogen.dir/build
.PHONY : test_mouse_autogen/fast

#=============================================================================
# Target rules for targets named test_input_autogen_timestamp_deps

# Build rule for target.
test_input_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_input_autogen_timestamp_deps
.PHONY : test_input_autogen_timestamp_deps

# fast build rule for target.
test_input_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_input_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_input_autogen_timestamp_deps.dir/build
.PHONY : test_input_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_input_autogen

# Build rule for target.
test_input_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_input_autogen
.PHONY : test_input_autogen

# fast build rule for target.
test_input_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_input_autogen.dir/build.make tests/CMakeFiles/test_input_autogen.dir/build
.PHONY : test_input_autogen/fast

#=============================================================================
# Target rules for targets named test_splits_autogen_timestamp_deps

# Build rule for target.
test_splits_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_splits_autogen_timestamp_deps
.PHONY : test_splits_autogen_timestamp_deps

# fast build rule for target.
test_splits_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_splits_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_splits_autogen_timestamp_deps.dir/build
.PHONY : test_splits_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_splits_autogen

# Build rule for target.
test_splits_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_splits_autogen
.PHONY : test_splits_autogen

# fast build rule for target.
test_splits_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_splits_autogen.dir/build.make tests/CMakeFiles/test_splits_autogen.dir/build
.PHONY : test_splits_autogen/fast

#=============================================================================
# Target rules for targets named test_splits_gl_autogen_timestamp_deps

# Build rule for target.
test_splits_gl_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_splits_gl_autogen_timestamp_deps
.PHONY : test_splits_gl_autogen_timestamp_deps

# fast build rule for target.
test_splits_gl_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_splits_gl_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_splits_gl_autogen_timestamp_deps.dir/build
.PHONY : test_splits_gl_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_splits_gl_autogen

# Build rule for target.
test_splits_gl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_splits_gl_autogen
.PHONY : test_splits_gl_autogen

# fast build rule for target.
test_splits_gl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_splits_gl_autogen.dir/build.make tests/CMakeFiles/test_splits_gl_autogen.dir/build
.PHONY : test_splits_gl_autogen/fast

#=============================================================================
# Target rules for targets named test_scroll_gl_autogen_timestamp_deps

# Build rule for target.
test_scroll_gl_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scroll_gl_autogen_timestamp_deps
.PHONY : test_scroll_gl_autogen_timestamp_deps

# fast build rule for target.
test_scroll_gl_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_scroll_gl_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_scroll_gl_autogen_timestamp_deps.dir/build
.PHONY : test_scroll_gl_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_scroll_gl_autogen

# Build rule for target.
test_scroll_gl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scroll_gl_autogen
.PHONY : test_scroll_gl_autogen

# fast build rule for target.
test_scroll_gl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_scroll_gl_autogen.dir/build.make tests/CMakeFiles/test_scroll_gl_autogen.dir/build
.PHONY : test_scroll_gl_autogen/fast

#=============================================================================
# Target rules for targets named test_render_autogen_timestamp_deps

# Build rule for target.
test_render_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_render_autogen_timestamp_deps
.PHONY : test_render_autogen_timestamp_deps

# fast build rule for target.
test_render_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_render_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_render_autogen_timestamp_deps.dir/build
.PHONY : test_render_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_render_autogen

# Build rule for target.
test_render_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_render_autogen
.PHONY : test_render_autogen

# fast build rule for target.
test_render_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_render_autogen.dir/build.make tests/CMakeFiles/test_render_autogen.dir/build
.PHONY : test_render_autogen/fast

#=============================================================================
# Target rules for targets named test_config_autogen_timestamp_deps

# Build rule for target.
test_config_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config_autogen_timestamp_deps
.PHONY : test_config_autogen_timestamp_deps

# fast build rule for target.
test_config_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_config_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_config_autogen_timestamp_deps.dir/build
.PHONY : test_config_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_config_autogen

# Build rule for target.
test_config_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config_autogen
.PHONY : test_config_autogen

# fast build rule for target.
test_config_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_config_autogen.dir/build.make tests/CMakeFiles/test_config_autogen.dir/build
.PHONY : test_config_autogen/fast

#=============================================================================
# Target rules for targets named test_tabbar_autogen_timestamp_deps

# Build rule for target.
test_tabbar_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tabbar_autogen_timestamp_deps
.PHONY : test_tabbar_autogen_timestamp_deps

# fast build rule for target.
test_tabbar_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_tabbar_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/test_tabbar_autogen_timestamp_deps.dir/build
.PHONY : test_tabbar_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_tabbar_autogen

# Build rule for target.
test_tabbar_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tabbar_autogen
.PHONY : test_tabbar_autogen

# fast build rule for target.
test_tabbar_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_tabbar_autogen.dir/build.make tests/CMakeFiles/test_tabbar_autogen.dir/build
.PHONY : test_tabbar_autogen/fast

ratty_autogen/3YJK5W5UP7/qrc_config.o: ratty_autogen/3YJK5W5UP7/qrc_config.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_config.o

# target to build an object file
ratty_autogen/3YJK5W5UP7/qrc_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_config.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_config.cpp.o

ratty_autogen/3YJK5W5UP7/qrc_config.i: ratty_autogen/3YJK5W5UP7/qrc_config.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_config.i

# target to preprocess a source file
ratty_autogen/3YJK5W5UP7/qrc_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_config.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_config.cpp.i

ratty_autogen/3YJK5W5UP7/qrc_config.s: ratty_autogen/3YJK5W5UP7/qrc_config.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_config.s

# target to generate assembly for a file
ratty_autogen/3YJK5W5UP7/qrc_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_config.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_config.cpp.s

ratty_autogen/3YJK5W5UP7/qrc_fonts.o: ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_fonts.o

# target to build an object file
ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.o

ratty_autogen/3YJK5W5UP7/qrc_fonts.i: ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_fonts.i

# target to preprocess a source file
ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.i

ratty_autogen/3YJK5W5UP7/qrc_fonts.s: ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_fonts.s

# target to generate assembly for a file
ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_fonts.cpp.s

ratty_autogen/3YJK5W5UP7/qrc_keybindings.o: ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_keybindings.o

# target to build an object file
ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.o

ratty_autogen/3YJK5W5UP7/qrc_keybindings.i: ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_keybindings.i

# target to preprocess a source file
ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.i

ratty_autogen/3YJK5W5UP7/qrc_keybindings.s: ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_keybindings.s

# target to generate assembly for a file
ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_keybindings.cpp.s

ratty_autogen/3YJK5W5UP7/qrc_shaders.o: ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.o

# target to build an object file
ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.o

ratty_autogen/3YJK5W5UP7/qrc_shaders.i: ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.i

# target to preprocess a source file
ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.i

ratty_autogen/3YJK5W5UP7/qrc_shaders.s: ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.s

# target to generate assembly for a file
ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_shaders.cpp.s

ratty_autogen/3YJK5W5UP7/qrc_themes.o: ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_themes.o

# target to build an object file
ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.o
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.o

ratty_autogen/3YJK5W5UP7/qrc_themes.i: ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_themes.i

# target to preprocess a source file
ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.i
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.i

ratty_autogen/3YJK5W5UP7/qrc_themes.s: ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_themes.s

# target to generate assembly for a file
ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.s
.PHONY : ratty_autogen/3YJK5W5UP7/qrc_themes.cpp.s

ratty_autogen/mocs_compilation.o: ratty_autogen/mocs_compilation.cpp.o
.PHONY : ratty_autogen/mocs_compilation.o

# target to build an object file
ratty_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/mocs_compilation.cpp.o
.PHONY : ratty_autogen/mocs_compilation.cpp.o

ratty_autogen/mocs_compilation.i: ratty_autogen/mocs_compilation.cpp.i
.PHONY : ratty_autogen/mocs_compilation.i

# target to preprocess a source file
ratty_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/mocs_compilation.cpp.i
.PHONY : ratty_autogen/mocs_compilation.cpp.i

ratty_autogen/mocs_compilation.s: ratty_autogen/mocs_compilation.cpp.s
.PHONY : ratty_autogen/mocs_compilation.s

# target to generate assembly for a file
ratty_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/ratty_autogen/mocs_compilation.cpp.s
.PHONY : ratty_autogen/mocs_compilation.cpp.s

src/config/chrome.o: src/config/chrome.cpp.o
.PHONY : src/config/chrome.o

# target to build an object file
src/config/chrome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/chrome.cpp.o
.PHONY : src/config/chrome.cpp.o

src/config/chrome.i: src/config/chrome.cpp.i
.PHONY : src/config/chrome.i

# target to preprocess a source file
src/config/chrome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/chrome.cpp.i
.PHONY : src/config/chrome.cpp.i

src/config/chrome.s: src/config/chrome.cpp.s
.PHONY : src/config/chrome.s

# target to generate assembly for a file
src/config/chrome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/chrome.cpp.s
.PHONY : src/config/chrome.cpp.s

src/config/config.o: src/config/config.cpp.o
.PHONY : src/config/config.o

# target to build an object file
src/config/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/config.cpp.o
.PHONY : src/config/config.cpp.o

src/config/config.i: src/config/config.cpp.i
.PHONY : src/config/config.i

# target to preprocess a source file
src/config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/config.cpp.i
.PHONY : src/config/config.cpp.i

src/config/config.s: src/config/config.cpp.s
.PHONY : src/config/config.s

# target to generate assembly for a file
src/config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/config.cpp.s
.PHONY : src/config/config.cpp.s

src/config/theme.o: src/config/theme.cpp.o
.PHONY : src/config/theme.o

# target to build an object file
src/config/theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/theme.cpp.o
.PHONY : src/config/theme.cpp.o

src/config/theme.i: src/config/theme.cpp.i
.PHONY : src/config/theme.i

# target to preprocess a source file
src/config/theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/theme.cpp.i
.PHONY : src/config/theme.cpp.i

src/config/theme.s: src/config/theme.cpp.s
.PHONY : src/config/theme.s

# target to generate assembly for a file
src/config/theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/config/theme.cpp.s
.PHONY : src/config/theme.cpp.s

src/core/mouse.o: src/core/mouse.cpp.o
.PHONY : src/core/mouse.o

# target to build an object file
src/core/mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/mouse.cpp.o
.PHONY : src/core/mouse.cpp.o

src/core/mouse.i: src/core/mouse.cpp.i
.PHONY : src/core/mouse.i

# target to preprocess a source file
src/core/mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/mouse.cpp.i
.PHONY : src/core/mouse.cpp.i

src/core/mouse.s: src/core/mouse.cpp.s
.PHONY : src/core/mouse.s

# target to generate assembly for a file
src/core/mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/mouse.cpp.s
.PHONY : src/core/mouse.cpp.s

src/core/palette.o: src/core/palette.cpp.o
.PHONY : src/core/palette.o

# target to build an object file
src/core/palette.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/palette.cpp.o
.PHONY : src/core/palette.cpp.o

src/core/palette.i: src/core/palette.cpp.i
.PHONY : src/core/palette.i

# target to preprocess a source file
src/core/palette.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/palette.cpp.i
.PHONY : src/core/palette.cpp.i

src/core/palette.s: src/core/palette.cpp.s
.PHONY : src/core/palette.s

# target to generate assembly for a file
src/core/palette.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/palette.cpp.s
.PHONY : src/core/palette.cpp.s

src/core/pty.o: src/core/pty.cpp.o
.PHONY : src/core/pty.o

# target to build an object file
src/core/pty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/pty.cpp.o
.PHONY : src/core/pty.cpp.o

src/core/pty.i: src/core/pty.cpp.i
.PHONY : src/core/pty.i

# target to preprocess a source file
src/core/pty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/pty.cpp.i
.PHONY : src/core/pty.cpp.i

src/core/pty.s: src/core/pty.cpp.s
.PHONY : src/core/pty.s

# target to generate assembly for a file
src/core/pty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/pty.cpp.s
.PHONY : src/core/pty.cpp.s

src/core/screen.o: src/core/screen.cpp.o
.PHONY : src/core/screen.o

# target to build an object file
src/core/screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/screen.cpp.o
.PHONY : src/core/screen.cpp.o

src/core/screen.i: src/core/screen.cpp.i
.PHONY : src/core/screen.i

# target to preprocess a source file
src/core/screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/screen.cpp.i
.PHONY : src/core/screen.cpp.i

src/core/screen.s: src/core/screen.cpp.s
.PHONY : src/core/screen.s

# target to generate assembly for a file
src/core/screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/screen.cpp.s
.PHONY : src/core/screen.cpp.s

src/core/terminal_emulator.o: src/core/terminal_emulator.cpp.o
.PHONY : src/core/terminal_emulator.o

# target to build an object file
src/core/terminal_emulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/terminal_emulator.cpp.o
.PHONY : src/core/terminal_emulator.cpp.o

src/core/terminal_emulator.i: src/core/terminal_emulator.cpp.i
.PHONY : src/core/terminal_emulator.i

# target to preprocess a source file
src/core/terminal_emulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/terminal_emulator.cpp.i
.PHONY : src/core/terminal_emulator.cpp.i

src/core/terminal_emulator.s: src/core/terminal_emulator.cpp.s
.PHONY : src/core/terminal_emulator.s

# target to generate assembly for a file
src/core/terminal_emulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/terminal_emulator.cpp.s
.PHONY : src/core/terminal_emulator.cpp.s

src/core/terminal_session.o: src/core/terminal_session.cpp.o
.PHONY : src/core/terminal_session.o

# target to build an object file
src/core/terminal_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/terminal_session.cpp.o
.PHONY : src/core/terminal_session.cpp.o

src/core/terminal_session.i: src/core/terminal_session.cpp.i
.PHONY : src/core/terminal_session.i

# target to preprocess a source file
src/core/terminal_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/terminal_session.cpp.i
.PHONY : src/core/terminal_session.cpp.i

src/core/terminal_session.s: src/core/terminal_session.cpp.s
.PHONY : src/core/terminal_session.s

# target to generate assembly for a file
src/core/terminal_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/terminal_session.cpp.s
.PHONY : src/core/terminal_session.cpp.s

src/core/vt_parser.o: src/core/vt_parser.cpp.o
.PHONY : src/core/vt_parser.o

# target to build an object file
src/core/vt_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/vt_parser.cpp.o
.PHONY : src/core/vt_parser.cpp.o

src/core/vt_parser.i: src/core/vt_parser.cpp.i
.PHONY : src/core/vt_parser.i

# target to preprocess a source file
src/core/vt_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/vt_parser.cpp.i
.PHONY : src/core/vt_parser.cpp.i

src/core/vt_parser.s: src/core/vt_parser.cpp.s
.PHONY : src/core/vt_parser.s

# target to generate assembly for a file
src/core/vt_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/core/vt_parser.cpp.s
.PHONY : src/core/vt_parser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render/box_drawing.o: src/render/box_drawing.cpp.o
.PHONY : src/render/box_drawing.o

# target to build an object file
src/render/box_drawing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/box_drawing.cpp.o
.PHONY : src/render/box_drawing.cpp.o

src/render/box_drawing.i: src/render/box_drawing.cpp.i
.PHONY : src/render/box_drawing.i

# target to preprocess a source file
src/render/box_drawing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/box_drawing.cpp.i
.PHONY : src/render/box_drawing.cpp.i

src/render/box_drawing.s: src/render/box_drawing.cpp.s
.PHONY : src/render/box_drawing.s

# target to generate assembly for a file
src/render/box_drawing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/box_drawing.cpp.s
.PHONY : src/render/box_drawing.cpp.s

src/render/font_manager.o: src/render/font_manager.cpp.o
.PHONY : src/render/font_manager.o

# target to build an object file
src/render/font_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/font_manager.cpp.o
.PHONY : src/render/font_manager.cpp.o

src/render/font_manager.i: src/render/font_manager.cpp.i
.PHONY : src/render/font_manager.i

# target to preprocess a source file
src/render/font_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/font_manager.cpp.i
.PHONY : src/render/font_manager.cpp.i

src/render/font_manager.s: src/render/font_manager.cpp.s
.PHONY : src/render/font_manager.s

# target to generate assembly for a file
src/render/font_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/font_manager.cpp.s
.PHONY : src/render/font_manager.cpp.s

src/render/gl_renderer.o: src/render/gl_renderer.cpp.o
.PHONY : src/render/gl_renderer.o

# target to build an object file
src/render/gl_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/gl_renderer.cpp.o
.PHONY : src/render/gl_renderer.cpp.o

src/render/gl_renderer.i: src/render/gl_renderer.cpp.i
.PHONY : src/render/gl_renderer.i

# target to preprocess a source file
src/render/gl_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/gl_renderer.cpp.i
.PHONY : src/render/gl_renderer.cpp.i

src/render/gl_renderer.s: src/render/gl_renderer.cpp.s
.PHONY : src/render/gl_renderer.s

# target to generate assembly for a file
src/render/gl_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/gl_renderer.cpp.s
.PHONY : src/render/gl_renderer.cpp.s

src/render/glyph_atlas.o: src/render/glyph_atlas.cpp.o
.PHONY : src/render/glyph_atlas.o

# target to build an object file
src/render/glyph_atlas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/glyph_atlas.cpp.o
.PHONY : src/render/glyph_atlas.cpp.o

src/render/glyph_atlas.i: src/render/glyph_atlas.cpp.i
.PHONY : src/render/glyph_atlas.i

# target to preprocess a source file
src/render/glyph_atlas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/glyph_atlas.cpp.i
.PHONY : src/render/glyph_atlas.cpp.i

src/render/glyph_atlas.s: src/render/glyph_atlas.cpp.s
.PHONY : src/render/glyph_atlas.s

# target to generate assembly for a file
src/render/glyph_atlas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/glyph_atlas.cpp.s
.PHONY : src/render/glyph_atlas.cpp.s

src/render/terminal_renderer.o: src/render/terminal_renderer.cpp.o
.PHONY : src/render/terminal_renderer.o

# target to build an object file
src/render/terminal_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/terminal_renderer.cpp.o
.PHONY : src/render/terminal_renderer.cpp.o

src/render/terminal_renderer.i: src/render/terminal_renderer.cpp.i
.PHONY : src/render/terminal_renderer.i

# target to preprocess a source file
src/render/terminal_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/terminal_renderer.cpp.i
.PHONY : src/render/terminal_renderer.cpp.i

src/render/terminal_renderer.s: src/render/terminal_renderer.cpp.s
.PHONY : src/render/terminal_renderer.s

# target to generate assembly for a file
src/render/terminal_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/render/terminal_renderer.cpp.s
.PHONY : src/render/terminal_renderer.cpp.s

src/ui/input_handler.o: src/ui/input_handler.cpp.o
.PHONY : src/ui/input_handler.o

# target to build an object file
src/ui/input_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/input_handler.cpp.o
.PHONY : src/ui/input_handler.cpp.o

src/ui/input_handler.i: src/ui/input_handler.cpp.i
.PHONY : src/ui/input_handler.i

# target to preprocess a source file
src/ui/input_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/input_handler.cpp.i
.PHONY : src/ui/input_handler.cpp.i

src/ui/input_handler.s: src/ui/input_handler.cpp.s
.PHONY : src/ui/input_handler.s

# target to generate assembly for a file
src/ui/input_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/input_handler.cpp.s
.PHONY : src/ui/input_handler.cpp.s

src/ui/main_window.o: src/ui/main_window.cpp.o
.PHONY : src/ui/main_window.o

# target to build an object file
src/ui/main_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/main_window.cpp.o
.PHONY : src/ui/main_window.cpp.o

src/ui/main_window.i: src/ui/main_window.cpp.i
.PHONY : src/ui/main_window.i

# target to preprocess a source file
src/ui/main_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/main_window.cpp.i
.PHONY : src/ui/main_window.cpp.i

src/ui/main_window.s: src/ui/main_window.cpp.s
.PHONY : src/ui/main_window.s

# target to generate assembly for a file
src/ui/main_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/main_window.cpp.s
.PHONY : src/ui/main_window.cpp.s

src/ui/split_container.o: src/ui/split_container.cpp.o
.PHONY : src/ui/split_container.o

# target to build an object file
src/ui/split_container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/split_container.cpp.o
.PHONY : src/ui/split_container.cpp.o

src/ui/split_container.i: src/ui/split_container.cpp.i
.PHONY : src/ui/split_container.i

# target to preprocess a source file
src/ui/split_container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/split_container.cpp.i
.PHONY : src/ui/split_container.cpp.i

src/ui/split_container.s: src/ui/split_container.cpp.s
.PHONY : src/ui/split_container.s

# target to generate assembly for a file
src/ui/split_container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/split_container.cpp.s
.PHONY : src/ui/split_container.cpp.s

src/ui/tab_bar.o: src/ui/tab_bar.cpp.o
.PHONY : src/ui/tab_bar.o

# target to build an object file
src/ui/tab_bar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/tab_bar.cpp.o
.PHONY : src/ui/tab_bar.cpp.o

src/ui/tab_bar.i: src/ui/tab_bar.cpp.i
.PHONY : src/ui/tab_bar.i

# target to preprocess a source file
src/ui/tab_bar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/tab_bar.cpp.i
.PHONY : src/ui/tab_bar.cpp.i

src/ui/tab_bar.s: src/ui/tab_bar.cpp.s
.PHONY : src/ui/tab_bar.s

# target to generate assembly for a file
src/ui/tab_bar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/tab_bar.cpp.s
.PHONY : src/ui/tab_bar.cpp.s

src/ui/terminal_widget.o: src/ui/terminal_widget.cpp.o
.PHONY : src/ui/terminal_widget.o

# target to build an object file
src/ui/terminal_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_widget.cpp.o
.PHONY : src/ui/terminal_widget.cpp.o

src/ui/terminal_widget.i: src/ui/terminal_widget.cpp.i
.PHONY : src/ui/terminal_widget.i

# target to preprocess a source file
src/ui/terminal_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_widget.cpp.i
.PHONY : src/ui/terminal_widget.cpp.i

src/ui/terminal_widget.s: src/ui/terminal_widget.cpp.s
.PHONY : src/ui/terminal_widget.s

# target to generate assembly for a file
src/ui/terminal_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ratty.dir/build.make CMakeFiles/ratty.dir/src/ui/terminal_widget.cpp.s
.PHONY : src/ui/terminal_widget.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ratty_autogen"
	@echo "... ratty_autogen_timestamp_deps"
	@echo "... ratty_lib_autogen"
	@echo "... ratty_lib_autogen_timestamp_deps"
	@echo "... test_config_autogen"
	@echo "... test_config_autogen_timestamp_deps"
	@echo "... test_input_autogen"
	@echo "... test_input_autogen_timestamp_deps"
	@echo "... test_mouse_autogen"
	@echo "... test_mouse_autogen_timestamp_deps"
	@echo "... test_render_autogen"
	@echo "... test_render_autogen_timestamp_deps"
	@echo "... test_scroll_gl_autogen"
	@echo "... test_scroll_gl_autogen_timestamp_deps"
	@echo "... test_splits_autogen"
	@echo "... test_splits_autogen_timestamp_deps"
	@echo "... test_splits_gl_autogen"
	@echo "... test_splits_gl_autogen_timestamp_deps"
	@echo "... test_tabbar_autogen"
	@echo "... test_tabbar_autogen_timestamp_deps"
	@echo "... test_terminal_autogen"
	@echo "... test_terminal_autogen_timestamp_deps"
	@echo "... ratty"
	@echo "... ratty_lib"
	@echo "... test_config"
	@echo "... test_input"
	@echo "... test_mouse"
	@echo "... test_render"
	@echo "... test_scroll_gl"
	@echo "... test_splits"
	@echo "... test_splits_gl"
	@echo "... test_tabbar"
	@echo "... test_terminal"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_config.o"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_config.i"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_config.s"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_fonts.o"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_fonts.i"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_fonts.s"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_keybindings.o"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_keybindings.i"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_keybindings.s"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_shaders.o"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_shaders.i"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_shaders.s"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_themes.o"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_themes.i"
	@echo "... ratty_autogen/3YJK5W5UP7/qrc_themes.s"
	@echo "... ratty_autogen/mocs_compilation.o"
	@echo "... ratty_autogen/mocs_compilation.i"
	@echo "... ratty_autogen/mocs_compilation.s"
	@echo "... src/config/chrome.o"
	@echo "... src/config/chrome.i"
	@echo "... src/config/chrome.s"
	@echo "... src/config/config.o"
	@echo "... src/config/config.i"
	@echo "... src/config/config.s"
	@echo "... src/config/theme.o"
	@echo "... src/config/theme.i"
	@echo "... src/config/theme.s"
	@echo "... src/core/mouse.o"
	@echo "... src/core/mouse.i"
	@echo "... src/core/mouse.s"
	@echo "... src/core/palette.o"
	@echo "... src/core/palette.i"
	@echo "... src/core/palette.s"
	@echo "... src/core/pty.o"
	@echo "... src/core/pty.i"
	@echo "... src/core/pty.s"
	@echo "... src/core/screen.o"
	@echo "... src/core/screen.i"
	@echo "... src/core/screen.s"
	@echo "... src/core/terminal_emulator.o"
	@echo "... src/core/terminal_emulator.i"
	@echo "... src/core/terminal_emulator.s"
	@echo "... src/core/terminal_session.o"
	@echo "... src/core/terminal_session.i"
	@echo "... src/core/terminal_session.s"
	@echo "... src/core/vt_parser.o"
	@echo "... src/core/vt_parser.i"
	@echo "... src/core/vt_parser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render/box_drawing.o"
	@echo "... src/render/box_drawing.i"
	@echo "... src/render/box_drawing.s"
	@echo "... src/render/font_manager.o"
	@echo "... src/render/font_manager.i"
	@echo "... src/render/font_manager.s"
	@echo "... src/render/gl_renderer.o"
	@echo "... src/render/gl_renderer.i"
	@echo "... src/render/gl_renderer.s"
	@echo "... src/render/glyph_atlas.o"
	@echo "... src/render/glyph_atlas.i"
	@echo "... src/render/glyph_atlas.s"
	@echo "... src/render/terminal_renderer.o"
	@echo "... src/render/terminal_renderer.i"
	@echo "... src/render/terminal_renderer.s"
	@echo "... src/ui/input_handler.o"
	@echo "... src/ui/input_handler.i"
	@echo "... src/ui/input_handler.s"
	@echo "... src/ui/main_window.o"
	@echo "... src/ui/main_window.i"
	@echo "... src/ui/main_window.s"
	@echo "... src/ui/split_container.o"
	@echo "... src/ui/split_container.i"
	@echo "... src/ui/split_container.s"
	@echo "... src/ui/tab_bar.o"
	@echo "... src/ui/tab_bar.i"
	@echo "... src/ui/tab_bar.s"
	@echo "... src/ui/terminal_widget.o"
	@echo "... src/ui/terminal_widget.i"
	@echo "... src/ui/terminal_widget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

